# Generated by Django 6.0.6 on 2026-06-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('STRIPE', 'Stripe Payment')], default='STRIPE', max_length=20),
        ),
    ]
