# Generated by Django 6.0.4 on 2026-05-04 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='settings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='settings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
